spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/celia
    username: root
    password: hihihihaha
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

# JWT Config
jwt:
  secret: secret
  expiration:
    ms: 86400000

